name: mdws
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.9
    - pip
    - jupyterlab=3
    - numpy
    - scipy
    - pandas
    - matplotlib
    - plotly
    - requests
    - python-dotenv
    - pyyaml
    - beautifulsoup4
    - html5lib
    - biopython
    # download data files
    - pooch
    - tqdm
    # linters and more
    - pylint
    - pycodestyle
    - pydocstyle
    - black
    - pip:
        - watermark
